### ISSUE TITLE
Headless No UI   Error 2

### ISSUE THREAD

**Issue by Katsukipp** [Nick088Official/FaceFusion-Online-Ports#17]
as before on issue #16  and now i got this error

`Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-3-697f155c453a>](https://localhost:8080/#) in <cell line: 13>()
     11 # Define the parent directory path
     12 FF_GD_name_enc = "==gZmJXex5mcV9VYiZnZoNlcw52U"
---> 13 FF_GD_name = _N_Vy9m_ (FF_GF_name_enc)
     14 parent_dir = f'/content/drive/MyDrive/{FF_GD_name}'
     15 

NameError: name 'FF_GF_name_enc' is not defined`

**Comment by Katsukipp** [comment]
> Could you retry now? it was a typo and should be fixed

now this shown up


Mounted at /content/drive
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-1-cb15c6c60ce4>](https://localhost:8080/#) in <cell line: 13>()
     11 # Define the parent directory path
     12 FF_GD_name_enc = "==gZmJXex5mcV9VYiZnZoNlcw52U"
---> 13 FF_GD_name = _N_Vy9m_(FF_GD_name_enc)
     14 parent_dir = f'/content/drive/MyDrive/{FF_GD_name}'
     15 

NameError: name '_N_Vy9m_' is not defined

**Comment by Nick088Official** [comment]
Did you restart the runtime after running the install cell?

**Comment by Katsukipp** [comment]
> Did you restart the runtime after running the install cell? Did you get a popup asking to restart the runtime while running the install cell on a branch?

oh, it's my mistake, after you update typo on the issu #16 i skip whole thing to just checking gdrive mount cell,  but when i run all cell from Install cell it did works, THANKS!
|


i have a minor question for me getting additional_options command error, should i ask here or should i make new issue thread ?

**Comment by Nick088Official** [comment]
> i have a minor question for me getting additional_options command error, should i ask here or should i make new issue thread ?

I noticed there was a problem in the additional options (which was that they changed --processors to --frame-processors), but that was solved at the same time that I updated the no ui one. Do you still get an issue? If so, you can just reopen this issue and tell me the problem if you want to

**Comment by Katsukipp** [comment]
> > i have a minor question for me getting additional_options command error, should i ask here or should i make new issue thread ?
> 
> I noticed there was a problem in the additional options, but that was solved at the same time that I updated the no ui one. Do you still get an issue? If so, you can just reopen this issue and tell me the problem if you want to


actually, i just try your latest update, and i got error like this, when i excecute processing

`/content
Traceback (most recent call last):
  File "/content/.program/run.py", line 7, in <module>
    from facefusion import core
  File "/content/.program/facefusion/core.py", line 8, in <module>
    from facefusion import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, voice_extractor, wording
  File "/content/.program/facefusion/content_analyser.py", line 9, in <module>
    import facefusion.globals
ModuleNotFoundError: No module named 'facefusion.globals'
/content/drive/MyDrive/FaceFusion_Headless/Outputs/Output.mp4 is a video file, going to encode it in the right way as in after the 2.3.0 version it encodes it weird.
Requirement already satisfied: ffmpeg in /usr/local/lib/python3.10/dist-packages (1.4)
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
/content/drive/MyDrive/FaceFusion_Headless/Outputs/Output.mp4: No such file or directory
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-7-b38152128525>](https://localhost:8080/#) in <cell line: 56>()
     66 
     67   get_ipython().system('$fix')
---> 68   os.remove(input_path) # remove the weird encoded file
     69   if output_path.endswith("_final"):
     70     new_filename = output_path.replace("_final", "")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/FaceFusion_Headless/Outputs/Output.mp4'`

**Comment by Katsukipp** [comment]
![Screenshot (6)](https://github.com/user-attachments/assets/4d9f55d0-4fbf-4bba-be7b-557bcfc62aa8)

**Comment by Katsukipp** [comment]
> ![Screenshot (6)](https://private-user-images.githubusercontent.com/182143800/369510832-4d9f55d0-4fbf-4bba-be7b-557bcfc62aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NTg0NDAsIm5iZiI6MTcyNjg1ODE0MCwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTEwODMyLTRkOWY1NWQwLTRmYmYtNGJiYS1iZTdiLTU1N2JjZmM2MmFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxODQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2QxYmI5NDJmMmI2NmU4YzczM2ViNzgyZTIyMmVmOWQyYWU2YjE1MjRiNWY1NmI1OTZmNDEyOTQ2NTI3NTFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KSBgziKdc4ot1-jayntU0ulljYTPbYsnTnb33nSsH-M)

is that because the addional_option error ?

**Comment by Nick088Official** [comment]
> ![Screenshot (6)](https://private-user-images.githubusercontent.com/182143800/369510832-4d9f55d0-4fbf-4bba-be7b-557bcfc62aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjI0OTUsIm5iZiI6MTcyNjg2MjE5NSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTEwODMyLTRkOWY1NWQwLTRmYmYtNGJiYS1iZTdiLTU1N2JjZmM2MmFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxOTU2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzQ0YzBlNjY5M2ZhOWIxZTFiMGEwYmQ4ZWUyYzViZWE0OWFhNGJkODI3YzZhZmZjMTViNTlhMjA3YzYzNDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3tkk74CLXe5-5v5h_eWb9hhX7EDI_icFhFtqL8WOrjU)

Did you change anything inside the .py files? and show me the additional inputs

**Comment by Katsukipp** [comment]
> > ![Screenshot (6)](https://private-user-images.githubusercontent.com/182143800/369510832-4d9f55d0-4fbf-4bba-be7b-557bcfc62aa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjI0OTUsIm5iZiI6MTcyNjg2MjE5NSwicGF0aCI6Ii8xODIxNDM4MDAvMzY5NTEwODMyLTRkOWY1NWQwLTRmYmYtNGJiYS1iZTdiLTU1N2JjZmM2MmFhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxOTU2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzQ0YzBlNjY5M2ZhOWIxZTFiMGEwYmQ4ZWUyYzViZWE0OWFhNGJkODI3YzZhZmZjMTViNTlhMjA3YzYzNDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3tkk74CLXe5-5v5h_eWb9hhX7EDI_icFhFtqL8WOrjU)
> 
> Did you change anything inside the .py files? and show me the additional inputs

sorry, i think i just mixedup the old and new py.. because i am opening more than one to try...

when i close my browser and start again it works.. i guess i closed this issue
thanks
