### ISSUE TITLE
RUN phase give Error.

### ISSUE THREAD

**Issue by MumbaiShiva** [Nick088Official/FaceFusion-Online-Ports#29]
good morning friends, today 27 October 2024 we are using your colab repository FaceFusion_UI, but when we are in the RUN phase it gives us this error:
Downloading: 100% 8.00/8.00 [00:00<00:00, 13.8B/s, file=open_nsfw.hash]
Downloading: 100% 22.5M/22.5M [00:00<00:00, 41.6MB/s, file=open_nsfw.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 18.3B/s, file=fairface.hash]
Downloading: 100% 81.2M/81.2M [00:00<00:00, 113MB/s, file=fairface.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 16.2B/s, file=yoloface_8n.hash]
Downloading: 100% 12.1M/12.1M [00:00<00:00, 21.8MB/s, file=yoloface_8n.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 15.4B/s, file=fan_68_5.hash]
Downloading: 100% 8.00/8.00 [00:00<00:00, 14.4B/s, file=2dfan4.hash]
Downloading: 100% 922k/922k [00:00<00:00, 1.64MB/s, file=fan_68_5.onnx]
Downloading: 100% 93.4M/93.4M [00:00<00:00, 105MB/s, file=2dfan4.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 14.5B/s, file=dfl_xseg.hash]
Downloading: 100% 8.00/8.00 [00:00<00:00, 15.1B/s, file=bisenet_resnet_34.hash]
Downloading: 100% 67.1M/67.1M [00:00<00:00, 90.0MB/s, file=dfl_xseg.onnx]
Downloading: 100% 89.3M/89.3M [00:01<00:00, 84.7MB/s, file=bisenet_resnet_34.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 14.4B/s, file=arcface_w600k_r50.hash]
Downloading: 100% 166M/166M [00:01<00:00, 142MB/s, file=arcface_w600k_r50.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 14.8B/s, file=kim_vocal_2.hash]
Downloading: 100% 63.7M/63.7M [00:00<00:00, 80.3MB/s, file=kim_vocal_2.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 14.4B/s, file=inswapper_128_fp16.hash]
Downloading: 100% 265M/265M [00:01<00:00, 151MB/s, file=inswapper_128_fp16.onnx]
Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

Traceback (most recent call last):
  File "/content/.program/run.py", line 10, in <module>
    core.cli()
  File "/content/.program/PROGRAM/core.py", line 41, in cli
    route(args)
  File "/content/.program/PROGRAM/core.py", line 68, in route
    ui.launch()
  File "/content/.program/PROGRAM/uis/core.py", line 82, in launch
    with gradio.Blocks(theme = get_theme(), css = get_css(), title = metadata.get('name') + ' ' + metadata.get('version'), fill_width = True) as ui:
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1082, in __init__
    self.queue()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2149, in queue
    self.app = routes.App.create_app(self)
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 347, in create_app
    def login(form_data: OAuth2PasswordRequestForm = Depends()):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 994, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 933, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 554, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 284, in get_dependant
    sub_dependant = get_param_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 118, in get_param_sub_dependant
    return get_sub_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 154, in get_sub_dependant
    sub_dependant = get_dependant(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 277, in get_dependant
    param_details = analyze_param(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 474, in analyze_param
    ensure_multipart_is_installed()
  File "/usr/local/lib/python3.10/dist-packages/fastapi/dependencies/utils.py", line 107, in ensure_multipart_is_installed
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

Prodotti Colab a pagamento - Annulla i contratti qui
 

can you give us a reason? Thank you.

**Comment by Nick088Official** [comment]
> [MumbaiShiva](/MumbaiShiva)

https://github.com/Nick088Official/FaceFusion-Online-Ports/blob/main/README.md#update---october-27th-2024 Fixed it,

Also, if you are on the google colab free tier, I would suggest you to use Lightning.ai instead as it's more stable (as it allows deepfakes unlike colab.)
