### ISSUE TITLE
Running on Gradio, and adding FACE ENHANCER a lot of bugs showed in RUN box..........

### ISSUE THREAD

**Issue by MumbaiShiva** [Nick088Official/FaceFusion-Online-Ports#33]
Good morning friends, 
your Repository allows me to regularly enter Gradio, and have the FaceFusion 3.1.0 screen, but when in addition to "swapping face"
 I select "Face Enhancer" improvement...
 it gives me a whole series of errors in RUN box
 which I partly send to you.

Thanks if you want to help me.

Downloading: 100% 8.00/8.00 [00:00<00:00, 23.2B/s, download_providers=['github', 'huggingface'], file_name=open_nsfw.hash]
Downloading: 100% 22.5M/22.5M [00:00<00:00, 30.1MB/s, download_providers=['github', 'huggingface'], file_name=open_nsfw.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 23.1B/s, download_providers=['github', 'huggingface'], file_name=fairface.hash]
Downloading: 100% 81.2M/81.2M [00:01<00:00, 67.4MB/s, download_providers=['github', 'huggingface'], file_name=fairface.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 14.8B/s, download_providers=['github', 'huggingface'], file_name=yoloface_8n.hash]
Downloading: 100% 12.1M/12.1M [00:00<00:00, 20.3MB/s, download_providers=['github', 'huggingface'], file_name=yoloface_8n.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 16.6B/s, download_providers=['github', 'huggingface'], file_name=fan_68_5.hash]
Downloading: 100% 8.00/8.00 [00:00<00:00, 16.5B/s, download_providers=['github', 'huggingface'], file_name=2dfan4.hash]
Downloading: 100% 922k/922k [00:00<00:00, 1.80MB/s, download_providers=['github', 'huggingface'], file_name=fan_68_5.onnx]
Downloading: 100% 93.4M/93.4M [00:01<00:00, 74.2MB/s, download_providers=['github', 'huggingface'], file_name=2dfan4.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 15.9B/s, download_providers=['github', 'huggingface'], file_name=xseg_1.hash]
Downloading: 100% 8.00/8.00 [00:00<00:00, 16.3B/s, download_providers=['github', 'huggingface'], file_name=bisenet_resnet_34.hash]
Downloading: 100% 67.1M/67.1M [00:01<00:00, 64.6MB/s, download_providers=['github', 'huggingface'], file_name=xseg_1.onnx]
Downloading: 100% 89.3M/89.3M [00:01<00:00, 76.0MB/s, download_providers=['github', 'huggingface'], file_name=bisenet_resnet_34.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 16.0B/s, download_providers=['github', 'huggingface'], file_name=arcface_w600k_r50.hash]
Downloading: 100% 166M/166M [00:02<00:00, 83.5MB/s, download_providers=['github', 'huggingface'], file_name=arcface_w600k_r50.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 16.3B/s, download_providers=['github', 'huggingface'], file_name=kim_vocal_2.hash]
Downloading: 100% 63.7M/63.7M [00:01<00:00, 64.1MB/s, download_providers=['github', 'huggingface'], file_name=kim_vocal_2.onnx]
Downloading: 100% 8.00/8.00 [00:00<00:00, 16.7B/s, download_providers=['github', 'huggingface'], file_name=inswapper_128_fp16.hash]
Downloading: 100% 265M/265M [00:03<00:00, 92.6MB/s, download_providers=['github', 'huggingface'], file_name=inswapper_128_fp16.onnx]
* Running on local URL:  http://127.0.0.1:7860/
* Running on public URL: https://10d6547588af681c0b.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 321, in call_process_api
    with utils.MatplotlibBackendMananger():
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 1028, in __enter__
    import matplotlib
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 321, in call_process_api
    with utils.MatplotlibBackendMananger():
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 1037, in __exit__
    import matplotlib
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py", line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/ticker.py", line 143, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

**Comment by Nick088Official** [comment]
You diddn't even specify which port, I already told you last time, use the bug report template https://github.com/Nick088Official/FaceFusion-Online-Ports/issues/31#issuecomment-2473996530 else it will be an invalid issue.
